using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace IslandoftheDamned.tui.Views;

public partial class GameView
{

    public GameView()
    {
        InitializeComponent();
        button1.Clicked += () => MessageBox.Query("Hello", "Hello There!", "Ok");
    }
}
